couchpotato:
  image: tssgery/strato-couchpotato:latest
  restart: always
  ports:
    - "${EXPOSED_PORT}:5050"
  volumes:
    - "${CONFIGDIR}:/config"
    - "${VIDEODIR}:/videos"
    - "${DOWNLOADDIR}:/downloads"
