name: Apaxy
description: |
  Apache server with Apaxy, shows file listings in a pretty format
version: "0.1.0"
category: Web
maintainer: Eric Young
license: Apache, v2
projectURL: https://github.com/stratolinux/apaxy
